### ISSUE TITLE
Error when executing the script due to incorrect Powershell x86 execution policy

### ISSUE THREAD

**Issue by AdmiralRaccoon** [fabi-d/arubaoscx-prtg#1]
Hallo,
ich habe das Skript bei einem neuen Aruba 6200er Switch ausprobiert (Firmware 10.11), bekomme bei PRTG (aktueller Release) jedoch die Meldung:

XML: Das zurückgelieferte XML entspricht nicht dem erwarteten Schema. (Code: PE233) -- JSON: Das zurückgelieferte JSON entspricht nicht der erwarteten Struktur (No mapping for the Unicode character exists in the target multi-byte code page). (Code: PE231)

Irgendeine Idee wo man da schauen müsste?

Danke und Gruss
Philipp

**Comment by fabi-d** [comment]
Hallo Philipp,
du kannst in den Script-Sensor-Einstellungen das "Result Handling" konfigurieren und festlegen, dass das Ergebnis des Scripts (die XML-Ausgabe für PRTG) gespeichert wird. Aktiviere das dort am besten mal mit "Store result" und schau im PRTG-Verzeichnis\Logs\sensors nach, was nach der Abfrage rauskommt.

Sonst natürlich die Standard-Sachen:
- HTTPS-Server und REST-API aktiviert?
- auf dem Switch vorhandener Nutzer als Windows-Nutzer an das Script übergeben?
- Klappt vom Browser des PRTG-Server aus der Login am Switch-Webinterface mit den hinterlegten Daten?
- In den Sensoreinstellungen die Umgebungsvariablen gesetzt?

Viele Grüße
Fabian

**Comment by AdmiralRaccoon** [comment]
Moin, 
nachdem ich mir den Sensoroutput angeschaut habe, hab ich den Fehler gefunden: Das Powershell-script durfte nicht ausgeführt werden wegen der fehlenden digitalen SIgnatur. 
Das hab ich geändert und jetzt läuft es auch.

Danke für die Hilfe,
Grüsse Philipp

**Comment by fabi-d** [comment]
Hallo Philipp,

danke für die Rückmeldung!
Kannst du hier kurz reinschreiben, was du machen musstest, um das Script lauffähig zu bekommen?
Ich nehme an, du musstest du Execution-Policy ändern oder eine Ausnahme für das Script bauen?

Viele Grüße
Fabian

**Comment by AdmiralRaccoon** [comment]
Ja, wichtig ist bei PRTG wohl das in der x86 Powershell zu machen. Ich habe dann ein "Set-ExecutionPolicy bypass" gemacht

**Comment by fabi-d** [comment]
Das werde ich am Wochenende mal testen und in der Anleitung ergänzen. 
Aktuell füge ich dem Sensor noch eine Erkennung von ungespeicherten Änderungen hinzu, sodass immer ein Fehler angezeigt wird, wenn die Running-Config von der Startup-Config abweicht. 

![image](https://github.com/fabi-d/arubaoscx-prtg/assets/33769017/c548c6e0-4e70-484c-b181-e39e81715aa0)

Danach ist die Überprüfung der Transceiver (Sendeleistung, Empfangsleistung, Temperatur) geplant. 
Später vielleicht auch mal die Erreichbarkeit von TACACS-Servern oder RADIUS-Servern.

Fehlt dir sonst noch etwas, was noch überwacht werden sollte?

**Comment by AdmiralRaccoon** [comment]
Das mit der Config Saved Funktion finde ich auch sehr nützlich.
Wir sind bei uns grade dabei unsere Ur-Ur-Uralten HP ProCurve 53er Switche von 2004 (!) durch Arube 8100 / 6200 zu tauschen, deswegen kann ich noch nicht genau sagen was noch alles nützlich wäre zu überwachen, aber ich bleibe hier wachsam. :-)

ABer tolle Arbeit von Dir, die Standard SNMP Sensoren von PRTG selber fand ich jetzt nicht so nützlich, bzw. müsste man sich ja selber mit OIDs und MIBs was zusammenbasteln
